// src/lib/lmf/registry.ts
// Built-in provider specs. "custom" is a template for user-supplied OpenAI-compatible endpoints.

import type { ProviderSpec } from './types'

export const BUILT_IN_PROVIDERS: Record<string, ProviderSpec> = {
  openrouter: {
    id: 'openrouter',
    label: 'OpenRouter',
    kind: 'openai-compat',
    baseURL: 'https://openrouter.ai/api/v1',
    authStyle: 'bearer',
    defaultHeaders: { 'HTTP-Referer': 'https://maigenki.app', 'X-Title': 'mAIgenki' },
    tokenParam: 'max_tokens',
    supportsJsonResponseFormat: true,
    modelListPath: '/models',
    oauth: {
      authorizeURL: 'https://openrouter.ai/auth',
      exchangeURL: 'https://openrouter.ai/api/v1/auth/keys',
      method: 'pkce-s256',
    },
    keyURL: 'https://openrouter.ai/keys',
  },
  openai: {
    id: 'openai',
    label: 'OpenAI',
    kind: 'openai-compat',
    baseURL: 'https://api.openai.com/v1',
    authStyle: 'bearer',
    tokenParam: 'max_completion_tokens',
    supportsJsonResponseFormat: true,
    modelListPath: '/models',
    keyURL: 'https://platform.openai.com/api-keys',
  },
  groq: {
    id: 'groq',
    label: 'Groq',
    kind: 'openai-compat',
    baseURL: 'https://api.groq.com/openai/v1',
    authStyle: 'bearer',
    tokenParam: 'max_tokens',
    supportsJsonResponseFormat: true,
    modelListPath: '/models',
    keyURL: 'https://console.groq.com/keys',
  },
  mistral: {
    id: 'mistral',
    label: 'Mistral',
    kind: 'openai-compat',
    baseURL: 'https://api.mistral.ai/v1',
    authStyle: 'bearer',
    tokenParam: 'max_tokens',
    supportsJsonResponseFormat: true,
    modelListPath: '/models',
    keyURL: 'https://console.mistral.ai/api-keys',
  },
  deepseek: {
    id: 'deepseek',
    label: 'DeepSeek',
    kind: 'openai-compat',
    baseURL: 'https://api.deepseek.com/v1',
    authStyle: 'bearer',
    tokenParam: 'max_tokens',
    supportsJsonResponseFormat: true,
    modelListPath: '/models',
    keyURL: 'https://platform.deepseek.com/api_keys',
  },
  xai: {
    id: 'xai',
    label: 'xAI (Grok)',
    kind: 'openai-compat',
    baseURL: 'https://api.x.ai/v1',
    authStyle: 'bearer',
    tokenParam: 'max_tokens',
    supportsJsonResponseFormat: true,
    modelListPath: '/models',
    keyURL: 'https://console.x.ai',
  },
  together: {
    id: 'together',
    label: 'Together AI',
    kind: 'openai-compat',
    baseURL: 'https://api.together.xyz/v1',
    authStyle: 'bearer',
    tokenParam: 'max_tokens',
    supportsJsonResponseFormat: true,
    modelListPath: '/models',
    keyURL: 'https://api.together.ai/settings/api-keys',
  },
  ollama: {
    id: 'ollama',
    label: 'Ollama (local)',
    kind: 'openai-compat',
    baseURL: 'http://localhost:11434/v1',
    authStyle: 'none',
    tokenParam: 'max_tokens',
    supportsJsonResponseFormat: false,
    modelListPath: '/api/tags',
  },
  anthropic: {
    id: 'anthropic',
    label: 'Anthropic (Claude)',
    kind: 'anthropic',
    baseURL: 'https://api.anthropic.com',
    authStyle: 'x-api-key',
    defaultHeaders: {
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true',
    },
    tokenParam: 'max_tokens',
    supportsJsonResponseFormat: false,
    modelListPath: '/v1/models',
    keyURL: 'https://console.anthropic.com/settings/keys',
  },
  gemini: {
    id: 'gemini',
    label: 'Google Gemini',
    kind: 'gemini',
    baseURL: 'https://generativelanguage.googleapis.com',
    authStyle: 'x-goog-api-key',
    tokenParam: 'max_tokens',
    supportsJsonResponseFormat: true,
    modelListPath: '/v1beta/models',
    keyURL: 'https://aistudio.google.com/apikey',
  },
  custom: {
    id: 'custom',
    label: 'Custom endpoint',
    kind: 'openai-compat',
    baseURL: '',
    authStyle: 'bearer',
    tokenParam: 'max_tokens',
    supportsJsonResponseFormat: false,
    modelListPath: '/models',
  },
}

export function getProviderSpec(providerId: string): ProviderSpec | null {
  return BUILT_IN_PROVIDERS[providerId] ?? null
}
