export type PipelineDebugLevel = 'off' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
export type PipelineDebugCategory = 'pipeline' | 'pdf' | 'ocr' | 'llm' | 'db' | 'media' | 'ui'
export type PipelineDebugConfig = { level: PipelineDebugLevel; categories?: PipelineDebugCategory[]; output?: 'console' | 'memory' | 'both' }
declare global { var __MAIGENKI_DEBUG__: PipelineDebugConfig | undefined; var downloadPipelineDebugLog: (() => Promise<string | undefined>) | undefined; var clearPipelineDebugLog: (() => void) | undefined; var startPipelineDebugFile: (() => Promise<string | undefined>) | undefined }
const levelRank: Record<PipelineDebugLevel, number> = { off: 0, error: 1, warn: 2, info: 3, debug: 4, trace: 5 }
type Entry = { timestamp: string; level: string; category: string; event: string; details: Record<string, unknown> }
const entries: Entry[] = []
let fileName: string | undefined
let fileHandle: FileSystemFileHandle | undefined
let fileQueue: Promise<void> = Promise.resolve()
function stageFor(event: string, details: Record<string, unknown>): string { const label = typeof details.label === 'string' ? details.label : ''; if (label === 'structure-analysis') return 'Structural analysis'; if (label.startsWith('enrichment-chunk-')) return label.replace('enrichment-chunk-', 'Enrichment chunk '); if (event.startsWith('extraction') || event.startsWith('extract-') || event === 'bytes-loaded') return 'PDF extraction'; if (event.startsWith('redaction')) return 'PII redaction'; if (event.startsWith('inference')) return 'Clinical inference'; if (event.startsWith('persist') || event.startsWith('transaction')) return 'IndexedDB persistence'; if (event.startsWith('image-')) return 'Image capture and compression'; if (event.startsWith('llm-')) return 'LLM routing'; return 'Pipeline orchestration' }
function markdownLine(entry: Entry): string { const stage = String(entry.details.stage ?? 'Pipeline orchestration'); const elapsed = entry.details.elapsedMs == null ? '' : ` | ${entry.details.elapsedMs} ms elapsed`; return `- **${entry.timestamp}** — **${stage}** — \`${entry.level}/${entry.category}/${entry.event}\`${elapsed} — ${JSON.stringify(entry.details)}\n` }
const isLocalDevelopment = typeof __DEV__ !== 'undefined' ? __DEV__ : process.env.NODE_ENV !== 'production'
export function getPipelineDebugConfig(): PipelineDebugConfig { return globalThis.__MAIGENKI_DEBUG__ ?? { level: isLocalDevelopment ? 'trace' : 'off', output: 'both' } }
export function setPipelineDebugConfig(config: PipelineDebugConfig): void { globalThis.__MAIGENKI_DEBUG__ = { ...config } }
export function pipelineDebugEnabled(level: PipelineDebugLevel, category: PipelineDebugCategory): boolean { const config = getPipelineDebugConfig(); return level !== 'off' && levelRank[config.level] >= levelRank[level] && (!config.categories || config.categories.includes(category)) }
export async function startPipelineDebugFile(): Promise<string | undefined> { const storage = typeof navigator !== 'undefined' ? navigator.storage as Navigator['storage'] & { getDirectory?: () => Promise<FileSystemDirectoryHandle> } : undefined; if (!storage?.getDirectory) return undefined; const directory = await storage.getDirectory(); const timestamp = new Date().toISOString().replace(/[:.]/g, '-'); fileName = `maigenki-pipeline-debug-${timestamp}.md`; fileHandle = await directory.getFileHandle(fileName, { create: true }); const writable = await fileHandle.createWritable(); await writable.write(`# mAIgenki pipeline debug\n\nStarted: ${new Date().toISOString()}\n\n`); await writable.close(); return fileName }
export function pipelineDebug(level: Exclude<PipelineDebugLevel, 'off'>, category: PipelineDebugCategory, event: string, details: Record<string, unknown> = {}): void { if (!pipelineDebugEnabled(level, category) || typeof console === 'undefined') return; const entry: Entry = { timestamp: new Date().toISOString(), level, category, event, details: { stage: stageFor(event, details), ...details } }; const config = getPipelineDebugConfig(); if (config.output !== 'console') entries.push(entry); if (fileHandle) fileQueue = fileQueue.then(async () => { const writable = await fileHandle?.createWritable({ keepExistingData: true }); if (!writable) return; const file = await fileHandle?.getFile(); await writable.seek(file?.size ?? 0); await writable.write(markdownLine(entry)); await writable.close() }).catch(() => undefined); if (config.output !== 'memory') { const method = level === 'error' ? console.error : level === 'warn' ? console.warn : console.info; method('[mAIgenki:pipeline]', entry) } }
export async function downloadPipelineDebugLog(): Promise<string | undefined> { await fileQueue; if (typeof document === 'undefined') return fileName; const markdown = entries.map(markdownLine).join(''); if (!markdown) return fileName; const timestamp = new Date().toISOString().replace(/[:.]/g, '-'); const downloadName = fileName ?? `maigenki-pipeline-debug-${timestamp}.md`; const url = URL.createObjectURL(new Blob([`# mAIgenki pipeline debug\n\n${markdown}`], { type: 'text/markdown' })); const link = document.createElement('a'); link.href = url; link.download = downloadName; link.click(); URL.revokeObjectURL(url); return downloadName }
export function clearPipelineDebugLog(): void { entries.length = 0 }
export function debugError(error: unknown): Record<string, string> { return error instanceof Error ? { name: error.name, message: error.message } : { message: String(error) } }
export function startPipelineDebugRun(runId = Math.random().toString(36).slice(2, 10)) { const startedAt = typeof performance !== 'undefined' ? performance.now() : Date.now(); const now = () => typeof performance !== 'undefined' ? performance.now() : Date.now(); const log = (level: Exclude<PipelineDebugLevel, 'off'>, category: PipelineDebugCategory, event: string, details: Record<string, unknown> = {}) => pipelineDebug(level, category, event, { runId, elapsedMs: Math.round(now() - startedAt), ...details }); return { runId, startedAt, log, elapsedMs: () => Math.round(now() - startedAt) } }
globalThis.downloadPipelineDebugLog = downloadPipelineDebugLog; globalThis.clearPipelineDebugLog = clearPipelineDebugLog; globalThis.startPipelineDebugFile = startPipelineDebugFile; if (isLocalDevelopment) void startPipelineDebugFile()
