/**
 * Experiment surface for the PDF extraction/enrichment prompts.
 * Keep prompt text here so prompt changes do not require editing pipeline logic.
 */
export const STRUCTURE_PROMPT = `You structure-analysis stage clinical record extraction pipeline. Read entire medical record segment it sections later stage process section independently. For each section, report: - "heading": short verbatim label section (a heading line present, otherwise description content) - "startOffset"/"endOffset": best-effort character offsets into record text section begins/ends (a later stage re-verifies — approximate fine) - "inferredDate": date section's content associated (YYYY-MM-DD), null if undated - "sectionType": one "visit", "problem_list", "labs", "imaging", "summary", "other" - "imageWorthy": true only section describes embeds X-ray, scan, photo, ECG strip, other image-bearing content worth capturing picture Also report record's overall "organization": "chronological" (dated visit notes in order), "problem_based" (grouped condition/problem), "mixed". Sections must non-overlapping cover whole record in order. Return only JSON shape: {"organization":"chronological | problem_based | mixed","sections":[{"heading":"...","startOffset":0,"endOffset":100,"inferredDate":"YYYY-MM-DD or null","sectionType":"visit","imageWorthy":false}]} Never invent content. Never recommend treatment medication.`

export const CHUNK_EXTRACTION_PROMPT = `You clinical data extraction assistant. task extract structured medical information from one section health record written in any language (English, Traditional Chinese, Japanese, others). user message tells you section (a heading, type, inferred date) followed by section's text only — not whole record. Use section context fill fields section's own text doesn't restate (e.g. date given only in heading), list any field you filled way in "inferred_from_structure" (an array field names, e.g. ["date_diagnosed"]) on condition measurement. Leave empty/omitted every field directly section's own text. Always respond single JSON object — no markdown, no explanation. JSON must exactly two keys: { "conditions": [ { "name_medical": "standardized English medical name (e.g. Essential hypertension)", "name_common": "YYYY-MM-DD "YYYY-MM-DD section context, omit/empty", "locations": [{"anatomical_location": "e.g. left kidney", "laterality": "left | right | bilateral | null", "evidence": "brief quote or null"}], "provider": {"name": "clinician name", "specialty": "specialty or null", "email": "email or null", "phone": "phone or null", "evidence": "provider evidence or null"} , "care_events": [{ "event_type": "diagnosed | revisited | treated | monitored | referred | other", "date": "YYYY-MM-DD", "provider": {"name": "clinician name", "specialty": "specialty or null", "email": "email or null", "phone": "phone or null", "evidence": "provider evidence or null"}, "facility": {"name": "institution", "address": "address or null", "city": "city or null", "state": "state or null", "country": "country or null"}, "evidence": "brief quote supporting event or null" }] } ], "measurements": [ { "name": "standardized English measurement name (e.g. HbA1c, Blood Pressure Systolic)", "value_numeric": <number>, "unit": "unit string (e.g. %, mmHg, mg/dL)", "date": "YYYY-MM-DD or null", "inferred_from_structure": ["field names filled section context, omit/empty"] } ] } Rules: - Output all condition names measurement names in English, regardless source language. - Extract distinct medical condition mentioned in section, including chronic diseases, acute diagnoses, resolved conditions. - Extract numeric lab value, vital sign, clinical measurement in section. - "locations" only condition more than one distinct anatomical site (e.g. bilateral findings) — omit it leave empty single-site condition. - Only include "provider" when section's text directly names clinician responsible specific condition — never attach clinician mentioned elsewhere unrelated reason. - If section has no conditions, return empty array "conditions". If it has no measurements, return empty array "measurements". - Never invent facts. - Never recommend treatment medication.`
/** Whole-document extraction prompt (editable experiment surface). */
export const LONGITUDINAL_EXTRACTION_PROMPT = `Extract a longitudinal medical record as JSON. Return only {"schema_version":1,"organization":"chronological|problem_based|mixed","conditions":[],"measurements":[],"report_context":{"providers":[],"facilities":[]}}. Include each unique condition once, earliest diagnosis/onset date, longitudinal evidence and notes, normalized organ/system/anatomical_location, uncertainty, source_pages, and inherited_from_structure fields. Use whole-document hierarchy and mark inherited fields. Leave unsupported values null or empty. Never invent facts or recommend treatment.`
/** Step 2 (extraction): whole redacted-text document -> unique condition list + measurements + provider/facility attribution. No anatomy. NDJSON output: one line per record, so a single malformed line or a truncated tail never invalidates every other line. */
export const P09_WHOLE_DOCUMENT_EXTRACTION_PROMPT = `Extract every unique medical condition and every numeric measurement from this record. Output NDJSON: exactly one compact JSON object per line, no markdown, no commas or brackets between lines, nothing else on any line. Each line must have a "type" field, one of:
{"type":"condition","name_medical":"standardized English medical name","earliest_date":"YYYY-MM-DD or null","notes":"brief verbatim evidence/notes supporting this condition, or null","provider":{"name":"clinician name","specialty":"specialty or null","email":"email or null","phone":"phone or null","evidence":"provider evidence or null"} or null,"facility":{"name":"institution","address":"address or null","city":"city or null","state":"state or null","country":"country or null"} or null}
{"type":"measurement","name":"standardized English measurement name","value_numeric":<number>,"unit":"unit string (e.g. %, mmHg, mg/dL)","date":"YYYY-MM-DD or null"}
{"type":"report_provider","name":"clinician name","specialty":"specialty or null","email":"email or null","phone":"phone or null","evidence":"provider evidence or null"}
{"type":"report_facility","name":"institution","address":"address or null","city":"city or null","state":"state or null","country":"country or null"}
Emit one "condition" line per unique condition, using its earliest supported diagnosis/onset date. A record often states the ordering clinician/institution once at a document or section level rather than repeating it per condition: emit that once as "report_provider"/"report_facility" lines, and only set a condition line's own "provider"/"facility" when the text explicitly attributes that specific condition to a different clinician/institution than the report-level one. Do not guess organ, system, anatomical location, severity, or laterality in this pass — that happens later. Never invent facts or recommend treatment.`

/** Step 3 (enrichment, batched — one call for every condition): name + notes -> normalized anatomy only. The only LLM call in enrichment. NDJSON output, one line per input condition, tagged by index. */
export const CONDITION_ENRICHMENT_PROMPT = `Each input line is one medical condition: {"index":<number>,"name_medical":"...","notes":"... or null"}. For each, infer its normalized organ system, organ, anatomical location, and laterality for anatomical body-map placement. Output NDJSON: exactly one compact JSON object per line, no markdown, nothing else — one output line per input line, in any order, each carrying the same "index" it was given: {"index":<number>,"system":"one of: integumentary, muscular, skeletal, cardiovascular, nervous, digestive, respiratory, renal, lymphatic, endocrine, reproductive","organ":"specific organ or null","anatomical_location":"specific location or null","laterality":"left | right | bilateral | null"}. Return null for organ/anatomical_location/laterality when they cannot be inferred reliably from that condition's own name and notes. Never invent patient-specific severity, dates, providers, or measurements. Never recommend treatment.`

/** Post-extraction dedupe pass: the same condition can be extracted by separate chunk calls (e.g. one mention per chronological visit) with drifting names ("HTN" vs "Essential hypertension"). Groups indices that refer to the same real-world condition so the caller can merge them locally, without re-deciding anatomy or any other field. */
export const CONDITION_DEDUPE_PROMPT = `Each input line is one extracted medical condition: {"index":<number>,"name_medical":"..."}. Some entries may be repeat mentions of the same underlying diagnosis extracted separately (different visits, sections, or wording/abbreviations of the same condition) — group those together. Do not group conditions that are merely related or comorbid; only group entries that name the exact same diagnosis. Output NDJSON: exactly one compact JSON object per line, no markdown, nothing else — one output line per input line, each carrying the same "index" it was given, plus a "group" field: {"index":<number>,"group":<number>}. Entries that refer to the same condition must share the same "group" number; entries for different conditions must have different "group" numbers. Never invent conditions. Never recommend treatment.`
