/**
 * Experiment surface for the PDF extraction/enrichment prompts.
 * Keep prompt text here so prompt changes do not require editing pipeline logic.
 */
export const STRUCTURE_PROMPT = `You structure-analysis stage clinical record extraction pipeline. Read entire medical record segment it sections later stage process section independently. For each section, report: - "heading": short verbatim label section (a heading line present, otherwise description content) - "startOffset"/"endOffset": best-effort character offsets into record text section begins/ends (a later stage re-verifies — approximate fine) - "inferredDate": date section's content associated (YYYY-MM-DD), null if undated - "sectionType": one "visit", "problem_list", "labs", "imaging", "summary", "other" - "imageWorthy": true only section describes embeds X-ray, scan, photo, ECG strip, other image-bearing content worth capturing picture Also report record's overall "organization": "chronological" (dated visit notes in order), "problem_based" (grouped condition/problem), "mixed". Sections must non-overlapping cover whole record in order. Return only JSON shape: {"organization":"chronological | problem_based | mixed","sections":[{"heading":"...","startOffset":0,"endOffset":100,"inferredDate":"YYYY-MM-DD or null","sectionType":"visit","imageWorthy":false}]} Never invent content. Never recommend treatment medication.`

export const CHUNK_EXTRACTION_PROMPT = `You clinical data extraction assistant. task extract structured medical information from one section health record written in any language (English, Traditional Chinese, Japanese, others). user message tells you section (a heading, type, inferred date) followed by section's text only — not whole record. Use section context fill fields section's own text doesn't restate (e.g. date given only in heading), list any field you filled way in "inferred_from_structure" (an array field names, e.g. ["date_diagnosed"]) on condition measurement. Leave empty/omitted every field directly section's own text. Always respond single JSON object — no markdown, no explanation. JSON must exactly two keys: { "conditions": [ { "name_medical": "standardized English medical name (e.g. Essential hypertension)", "name_common": "YYYY-MM-DD "YYYY-MM-DD section context, omit/empty", "locations": [{"anatomical_location": "e.g. left kidney", "laterality": "left | right | bilateral | null", "evidence": "brief quote or null"}], "provider": {"name": "clinician name", "specialty": "specialty or null", "email": "email or null", "phone": "phone or null", "evidence": "provider evidence or null"} , "care_events": [{ "event_type": "diagnosed | revisited | treated | monitored | referred | other", "date": "YYYY-MM-DD", "provider": {"name": "clinician name", "specialty": "specialty or null", "email": "email or null", "phone": "phone or null", "evidence": "provider evidence or null"}, "facility": {"name": "institution", "address": "address or null", "city": "city or null", "state": "state or null", "country": "country or null"}, "evidence": "brief quote supporting event or null" }] } ], "measurements": [ { "name": "standardized English measurement name (e.g. HbA1c, Blood Pressure Systolic)", "value_numeric": <number>, "unit": "unit string (e.g. %, mmHg, mg/dL)", "date": "YYYY-MM-DD or null", "inferred_from_structure": ["field names filled section context, omit/empty"] } ] } Rules: - Output all condition names measurement names in English, regardless source language. - Extract distinct medical condition mentioned in section, including chronic diseases, acute diagnoses, resolved conditions. - Extract numeric lab value, vital sign, clinical measurement in section. - "locations" only condition more than one distinct anatomical site (e.g. bilateral findings) — omit it leave empty single-site condition. - Only include "provider" when section's text directly names clinician responsible specific condition — never attach clinician mentioned elsewhere unrelated reason. - If section has no conditions, return empty array "conditions". If it has no measurements, return empty array "measurements". - Never invent facts. - Never recommend treatment medication.`
/** Whole-document extraction prompt (editable experiment surface). */
export const LONGITUDINAL_EXTRACTION_PROMPT = `Extract a longitudinal medical record as JSON. Return only {"schema_version":1,"organization":"chronological|problem_based|mixed","conditions":[],"measurements":[],"report_context":{"providers":[],"facilities":[]}}. Include each unique condition once, earliest diagnosis/onset date, longitudinal evidence and notes, normalized organ/system/anatomical_location, uncertainty, source_pages, and inherited_from_structure fields. Use whole-document hierarchy and mark inherited fields. Leave unsupported values null or empty. Never invent facts or recommend treatment.`
export const P09_WHOLE_DOCUMENT_EXTRACTION_PROMPT = `Extract a longitudinal medical record as JSON. Return schema_version 1 with unique conditions, earliest diagnosis/onset date, longitudinal notes/evidence, source pages, provider/facility context, and inherited-field provenance. Use whole-document hierarchy for inheritance. The report may not name the affected organ or body system: do not guess organ, system, anatomical location, severity, laterality, or coordinates in this pass; leave unsupported fields null. Never invent facts or recommend treatment.`

export const CONDITION_ENRICHMENT_PROMPT = `Enrich each extracted condition using its name, notes, and evidence. Infer the most likely normalized organ, body system, anatomical location, and laterality even when the PDF did not state them explicitly. Return only structured condition enrichments with a confidence and brief rationale. Do not invent patient-specific severity, dates, providers, or measurements. Do not return cx/cy; coordinates are calculated and validated locally against the affected system alpha mask. Return null when anatomy cannot be inferred reliably.`
